{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.labels.app }}-redis-policy
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.labels.app }}-redis
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.labels.app }}
      ports:
        - protocol: TCP
          port: 6379
{{- end }}
