apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-pp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-pp
  template:
    metadata:
      labels:
        app: redis-pp
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service-pp
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      
